### ISSUE TITLE
Regarding "def extract_ding_variable_features(model)" in utils.py

### ISSUE THREAD

**Issue by ghost** [Joey-Shen/pb-dfs#3]
Hi, there,

In utils.py, specifically for the function "extract_ding_variable_features(model)", it seems to me that "**model.getDingStateCols()**" is not callable, since the method getDingStateCol() is not available to see on Model Class Reference (i.e., [on SCIP Official website](https://scipopt.github.io/PySCIPOpt/docs/html/annotated.html) ). On the other hand, I did not find any definitions for this method. How can one make it executable successfully? 

I appreciate any help you can provide.

**Comment by yunzhuangshen** [comment]
Hi Xiangyu,

The **model.getDingStateCols()** is not provided by the official SCIPopt package, but it is coded by myself. The customized SCIPopt code is also provided for installation.
 
Specifically, the method **model.getDingStateCols()** starts at line 4476,  PB-DFS/PySCIPOpt/src/pyscipopt/scip.pyx.

Yunzhuang

**Comment by ghost** [comment]
Thanks for @Joey-Shen reply.

On the other hand, I may have one question regarding your paper. After reading your paper, if I understand it correctly, the proposed method not only configures the B&B to boost the DFS process but also can be a solution prediction solver, i.e., we can obtain an optimal solution according to the results outputted by the ML model. In this view, the trained model is like an "ML solver" working in an end-to-end fashion. Is this view correct？

Thanks, again!

**Comment by yunzhuangshen** [comment]
Hi Xiangyu,

The prediction of an ML model may not be the optimal solution or even a feasible solution, and we cannot guarantee that the ML prediction meets the constraints of a problem. Hence, I would not call it an "ML solver". 

To my understanding, end-to-end approaches typically refer to reinforcement learning (RL) methods, which takes sequential actions to build a solution. In the iterative process, RL masks off the invalid actions to ensure the feasibility of the constructed solution. Please also see [1].

[1] Bengio, Yoshua, Andrea Lodi, and Antoine Prouvost. "Machine learning for combinatorial optimization: a methodological tour d’horizon." European Journal of Operational Research 290.2 (2021): 405-421.
